### ISSUE TITLE
Can i use it on linux, mac os and Ios machines?

### ISSUE THREAD

**Issue by switchy7** [cybervaca/PsBoTelegram#4]
hello can i use it on MacOs Linux or IOS and androids or it is only for Windows?

**Comment by switchy7** [comment]
so no one can answer does it works on Linux or MacOS?

**Comment by cybervaca** [comment]
You mean controlling non-windows computers?

**Comment by cybervaca** [comment]
The script works from linux ,windows and macos. As for controlling systems other than windows, it is not possible with this script.

**Comment by cybervaca** [comment]
![imagen](https://user-images.githubusercontent.com/6973635/99386576-fd216700-28d2-11eb-8039-dcd7c9038cbc.png)

**Comment by cybervaca** [comment]
if you want to control other systems you will have to create it yourself.

**Comment by switchy7** [comment]
yes for example i need for linux or macos what i should do to create? can i integrate metasploit payload?

**Comment by cybervaca** [comment]
You should rewrite the code in a native linux or ios language. This code does not work for you

**Comment by switchy7** [comment]
generated code by your tool or i must rewrite the whole rat?

**Comment by switchy7** [comment]
i can generate linux payload but how put to connect via telegram

**Comment by switchy7** [comment]
do i need to generate new bot for every new slave?

**Comment by cybervaca** [comment]
I don't mean to be rude. But I already told you that this software only works in windows, if you want to do it for other systems try to read the source code and export it to python or the language you consider.
